org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.07.20

minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.21.9)

mod_version_major=0
mod_version_minor=11

mod_id=bluepower
mod_group_id="com.bluepowermod"
mod_name="Blue Power"
mod_license="GNU General Public License v3.0"
mod_authors="Quetzi, Zness, MineMaarten, K4Unl, Amadornes and MoreThanHidden"
mod_description="Work in progress mod aiming to reintroduce some missing 'glue' blocks from prior versions of modded Minecraft."

neo_version=21.8.36

jei_version=24.0.0.2
jade_version=jade-324717:5493270